# Generated by Django 3.1.6 on 2021-02-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Majice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.TextField()),
                ('model', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('admin', models.IntegerField()),
            ],
        ),
    ]
