# Generated by Django 3.1.6 on 2021-02-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='majice',
            name='cena',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patike',
            name='cena',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
