# Generated by Django 3.1.6 on 2021-02-17 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210217_0157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
