# Generated by Django 3.1.6 on 2021-02-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210217_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patike',
            name='cena',
            field=models.TextField(),
        ),
    ]
